version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: surfplanner-backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

  frontend:
    build:
      context: ./frontend
    container_name: surfplanner-frontend
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    depends_on:
      - backend

  db:
    image: mysql:8.0
    container_name: surfplanner-db
    restart: always
    env_file:
      - ./db/.env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
